-- Record the connection profile an Edit-and-Send request was COMMITTED against.
--
-- `generation_outbox` is durable but its dispatch is not a single event: the
-- same row can be dispatched from the POST handler, again from the periodic
-- retry tick after a backoff, and again from startup crash recovery, potentially
-- hours apart. Connection selection used to be re-read from live state
-- (`activeProfileId`, the `editAndSendAlwaysUseActiveConnection` opt-in, the
-- chat's `connection_profile_id` pin) on EVERY one of those ticks, so switching
-- the active profile retargeted a request the user had already committed.
-- Persisting the resolved id here makes the choice immutable for the life of the
-- request, which is the whole point of an outbox.
--
-- Deliberately NULLABLE with no UNIQUE constraint and no index:
--   * NULL is a first-class value. Rows committed before this column existed
--     have no recorded identity, and the dispatcher must keep resolving those
--     through the unchanged legacy ladder rather than failing them. The same
--     applies when resolution legitimately comes up empty at commit time.
--   * AGENTS.md forbids in-place UNIQUE via `ALTER TABLE` in SQLite (it would
--     require a table recreation), and uniqueness would be wrong anyway: many
--     requests share one connection.
--   * No index: the column is only ever read via the row itself, which is
--     already fetched by primary key / the existing (user_id, chat_id,
--     request_id) and generation_id lookups. An index would be dead weight on
--     the write path.
ALTER TABLE generation_outbox ADD COLUMN connection_id TEXT;
