import { useCallback, useEffect, useRef, useState } from 'react'
import type {
  MouseEvent as ReactMouseEvent,
  PointerEvent as ReactPointerEvent,
} from 'react'
import { getUiScale, renderedPxToLayoutPx } from '@/lib/uiScale'

export const DRAWER_TAB_VERTICAL_POSITION_MIN = 0
export const DRAWER_TAB_VERTICAL_POSITION_MAX = 70
export const DRAWER_TAB_DRAG_THRESHOLD_PX = 5

interface DrawerTabDragOptions {
  position: number
  onCommit: (position: number) => void
}

interface ActiveDrag {
  pointerId: number
  startClientX: number
  startClientY: number
  startPosition: number
  latestPosition: number
  viewportHeight: number
  uiScale: number
  moved: boolean
}

export function clampDrawerTabVerticalPosition(position: number): number {
  if (!Number.isFinite(position)) return DRAWER_TAB_VERTICAL_POSITION_MIN
  return Math.max(
    DRAWER_TAB_VERTICAL_POSITION_MIN,
    Math.min(DRAWER_TAB_VERTICAL_POSITION_MAX, Math.round(position)),
  )
}

export function drawerTabPositionFromRenderedDelta(
  startPosition: number,
  renderedDeltaY: number,
  viewportHeight: number,
  uiScale: number,
): number {
  if (!Number.isFinite(viewportHeight) || viewportHeight <= 0) {
    return clampDrawerTabVerticalPosition(startPosition)
  }
  const layoutDeltaY = renderedPxToLayoutPx(renderedDeltaY, uiScale)
  return clampDrawerTabVerticalPosition(startPosition + (layoutDeltaY / viewportHeight) * 100)
}

export function useDrawerTabDrag({ position, onCommit }: DrawerTabDragOptions) {
  const [draftPosition, setDraftPosition] = useState<number | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const activeDragRef = useRef<ActiveDrag | null>(null)
  const onCommitRef = useRef(onCommit)
  const suppressClickRef = useRef(false)
  const suppressClickTimerRef = useRef<number | null>(null)
  onCommitRef.current = onCommit

  const clearClickSuppression = useCallback(() => {
    suppressClickRef.current = false
    if (suppressClickTimerRef.current !== null) {
      window.clearTimeout(suppressClickTimerRef.current)
      suppressClickTimerRef.current = null
    }
  }, [])

  const suppressSyntheticClick = useCallback(() => {
    clearClickSuppression()
    suppressClickRef.current = true
    // A click generated by pointerup is dispatched before the next task. Clear
    // this guard afterwards so an absent synthetic click cannot eat a later tap.
    suppressClickTimerRef.current = window.setTimeout(clearClickSuppression, 0)
  }, [clearClickSuppression])

  const handlePointerDown = useCallback((event: ReactPointerEvent<HTMLButtonElement>) => {
    if (event.button !== 0 || event.isPrimary === false || activeDragRef.current) return
    const startPosition = clampDrawerTabVerticalPosition(position)
    activeDragRef.current = {
      pointerId: event.pointerId,
      startClientX: event.clientX,
      startClientY: event.clientY,
      startPosition,
      latestPosition: startPosition,
      viewportHeight: window.innerHeight,
      uiScale: getUiScale(),
      moved: false,
    }
    event.currentTarget.setPointerCapture?.(event.pointerId)
  }, [position])

  const handlePointerMove = useCallback((event: ReactPointerEvent<HTMLButtonElement>) => {
    const active = activeDragRef.current
    if (!active || active.pointerId !== event.pointerId) return

    if (!active.moved) {
      const deltaX = event.clientX - active.startClientX
      const deltaY = event.clientY - active.startClientY
      if (Math.hypot(deltaX, deltaY) < DRAWER_TAB_DRAG_THRESHOLD_PX) return
      active.moved = true
      setIsDragging(true)
    }

    event.preventDefault()
    const nextPosition = drawerTabPositionFromRenderedDelta(
      active.startPosition,
      event.clientY - active.startClientY,
      active.viewportHeight,
      active.uiScale,
    )
    active.latestPosition = nextPosition
    setDraftPosition(nextPosition)
  }, [])

  const finishDrag = useCallback((
    event: ReactPointerEvent<HTMLButtonElement>,
    suppressClick: boolean,
  ) => {
    const active = activeDragRef.current
    if (!active || active.pointerId !== event.pointerId) return

    activeDragRef.current = null
    setDraftPosition(null)
    setIsDragging(false)

    if (active.moved) {
      event.preventDefault()
      onCommitRef.current(active.latestPosition)
      if (suppressClick) suppressSyntheticClick()
    }

    if (event.currentTarget.hasPointerCapture?.(event.pointerId)) {
      event.currentTarget.releasePointerCapture?.(event.pointerId)
    }
  }, [suppressSyntheticClick])

  const handlePointerUp = useCallback(
    (event: ReactPointerEvent<HTMLButtonElement>) => finishDrag(event, true),
    [finishDrag],
  )

  const handlePointerCancel = useCallback(
    (event: ReactPointerEvent<HTMLButtonElement>) => finishDrag(event, false),
    [finishDrag],
  )

  const consumeSuppressedClick = useCallback((event: ReactMouseEvent<HTMLButtonElement>): boolean => {
    if (!suppressClickRef.current) return false
    event.preventDefault()
    event.stopPropagation()
    clearClickSuppression()
    return true
  }, [clearClickSuppression])

  useEffect(() => () => {
    activeDragRef.current = null
    clearClickSuppression()
  }, [clearClickSuppression])

  return {
    verticalPosition: draftPosition ?? clampDrawerTabVerticalPosition(position),
    isDragging,
    consumeSuppressedClick,
    pointerHandlers: {
      onPointerDown: handlePointerDown,
      onPointerMove: handlePointerMove,
      onPointerUp: handlePointerUp,
      onPointerCancel: handlePointerCancel,
      onLostPointerCapture: handlePointerCancel,
    },
  }
}
