export const goodbyeLines = [
  "See you, Space Cowboy.",
  "Whatever happens, happens.",
  "You're gonna carry that weight.",
  "The cake is a lie.",
  "It's dangerous to go alone.",
  "Your princess is in another castle.",
  "The right man in the wrong place can make all the difference.",
  "Rise and shine.",
  "Wake me when you need me.",
  "I used to be an adventurer like you.",
  "You died.",
  "Continue? 9... 8... 7...",
  "A winner is you.",
  "Fus Ro Dah.",
  "Stay a while and listen.",
  "Press F to pay respects.",
  "Sekiro has died 1,247 times.",
  "Reticulating splines.",
  "GG.",
  "I'll be back.",
  "This is the way.",
  "I have spoken.",
  "I could do this all day.",
  "Do. Or do not.",
  "You were never in control.",
  "That's no moon.",
  "Avengers... assemble.",
  "Winter is coming.",
  "The night is dark and full of terrors.",
  "Hodor.",
  "It's just a flesh wound.",
  "Nobody puts Baby in a corner.",
  "Nobody expects the Spanish Inquisition.",
  "There is no spoon.",
  "Swear to me.",
  "We're not in Kansas anymore.",
  "We accept the love we think we deserve.",
  "You cannot pass.",
  "Roads? Where we're going, we don't need roads.",
  "So it goes.",
  "Don't Panic.",
  "All was well.",
  "Not all those who wander are lost.",
  "Time is an illusion. Lunchtime doubly so.",
  "So long, and thanks for all the fish.",
  "The answer is 42.",
  "It was the best of times. It was the worst of times.",
  "It is a truth universally acknowledged.",
  "This is fine.",
  "One does not simply close a chat.",
  "It's over 9000.",
  "We don't talk about Bruno.",
  "I understood that reference.",
  "To be continued...",
  "No cap.",
  "It do be like that.",
  "Task failed successfully.",
  "Runner has left the chat.",
  "Main-character energy: powering down.",
  "The timeline has been muted. For now.",
  "This shutdown has excellent lore implications.",
  "Achievement unlocked: graceful exit.",
  "Quest complete. Returning to the main menu.",
  "Checkpoint reached. Progress saved.",
  "The save icon spins one last time.",
  "Respawning at the next deploy.",
  "Speedrun complete. No glitches were reported.",
  "The NPC has finished its dialogue tree.",
  "Party disbanded. Loot remains yours.",
  "The boss music has faded out.",
  "Inventory full of good intentions. Logging off.",
  "A wild shutdown appeared!",
  "Critical hit: clean exit.",
  "The controller has been set down dramatically.",
  "New game plus starts next time.",
  "BRB, touching grass.",
  "This is a certified log-off moment.",
  "The vibes have been archived.",
  "Plot twist: the process exited normally.",
  "The algorithm will remember this.",
  "No thoughts, just shutdown.",
  "It is giving: exit code zero.",
  "The group chat can carry on without us.",
  "In this house, we respect a clean teardown.",
  "The sequel hook is loading... eventually.",
  "Roll credits. Skip button unavailable.",
  "Post-credit scene: see you next run.",
  "The montage ends here.",
  "Fade to black. Cue the theme music.",
  "The chosen process has fulfilled its prophecy.",
  "May the logs be ever in your favor.",
  "Live long, process safely, and prosper.",
  "Be excellent to each other, even in production.",
  "The runner is going where no process has gone before.",
  "Not today, bugs. Tomorrow, probably.",
  "Runner was not the impostor.",
  "Creeper? Aw, shutdown.",
  "The nexus has fallen. GG.",
  "Victory Royale: graceful exit.",
  "The adventure log has been updated: runner exited.",
  "Maidenless no more. Offline, however.",
  "The next run starts when you're ready.",
  "The farm will be waiting tomorrow.",
  "Tom Nook has logged the departure.",
  "The vault is sealed. War never changes.",
  "The world has been saved and quit.",
  "The runner has entered the End.",
  "This process has gone hollow.",
  "Oof. Server closed.",
  "The payload reached its destination: shutdown.",
  "Wasted. (Exit code: 0.)",
  "The runner returns to orbit.",
  "Quest complete: close the application.",
  "Is this the real life? Is this just fantasy?",
  "Mr. Brightside has entered the chat. Then left.",
  "We will, we will rock you.",
  "Here I am. Rock you like a hurricane.",
  "Bohemian Rhapsody has 1.4 billion views. Make of that what you will.",
  "sudo shutdown -h now",
  "Goodbye, World.",
  "Exit code: 0",
  "HTTP 418: I'm a teapot.",
  "Connection terminated.",
  "Session expired. As all things must.",
  "Kernel panic - not syncing.",
  "Memory cleared. You never happened.",
  "Have you tried turning it off and on again?",
  "Error 404: Goodbye not found. Leaving anyway.",
  "git commit -m \"goodbye\"",
  "rm -rf ./feelings",
  "kill -9 [session]",
  "Low orbit established. Ejecting.",
  "See you on the other side.",
  "Until next time.",
  "Nothing is over. Nothing.",
  "Come back. Or don't. We're not your mom.",
  "Stay curious.",
  "You were a good session.",
] as const;
